name: snk
on:
  schedule:
    - cron: "8 3 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: nella17
          svg_out_path: dist/github-snake.svg
      - name: push github-snake.svg
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: snk
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
