name: Waka Readme

on:
  push:
    branches: 
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: nella17/waka-readme-stats@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_EDITORS: false
          SHOW_LOC_CHART: false
          SHOW_LANGUAGE: false
